#!/usr/bin/env python

import os
import subprocess
import argparse
import hashlib

TARGETS_DIR = "targets-ite2/"
PACKAGES_DIR = "packages/"
IN_TOTO_METADATA_DIR = "in-toto-metadata/"
PUBKEYS_DIR = "in-toto-pubkeys/"
# Define role
ROLE = "packages-and-in-toto-metadata-signer"


def main():
    raise NotImplementedError("This script is not implemented yet.")

    # Take package name as argument

    # Before uploading, you must change to the directory where the targets are stored

    # Define role and filenames that have to be passed to `../tuf-ite2/uploader/uploader` binary

    # uploader init (tofu)

    # upload package with its custom metadata

    # upload all the links corresponding for the package you uploaded


if __name__ == "__main__":
    main()
